#define R_MAGIC_ADDR 0x00
#define R_DEVICE_VERSION_ADDR 0x04
#define R_DEVICE_ID_ADDR 0x08
#define R_VENDOR_ID_ADDR 0x0c
#define R_DEVICE_FEATURES_ADDR 0x10
#define R_QUEUE_NUM_MAX_ADDR 0x34
#define R_INTERRUPT_STATUS_ADDR 0x60
#define R_CONFIG_GENERATION_ADDR 0xfc

#define RW_QUEUE_READY_ADDR 0x44
#define RW_DEVICE_STATUS_ADDR 0x70

#define W_DEVICE_FEATURES_SEL_ADDR 0x14
#define W_DRIVER_FEATURES_ADDR 0x20
#define W_DRIVER_FEATURES_SEL_ADDR 0x24
#define W_QUEUE_SEL_ADDR 0x30
#define W_QUEUE_NUM_ADDR 0x38
#define W_QUEUE_NOTIFY_ADDR 0x50
#define W_INTERRUPT_ACK_ADDR 0x64
#define W_QUEUE_DESC_LOW_ADDR 0x80
#define W_QUEUE_DESC_HIGH_ADDR 0x84
#define W_QUEUE_AVAIL_LOW_ADDR 0x90
#define W_QUEUE_AVAIL_HIGH_ADDR 0x94
#define W_QUEUE_USED_LOW_ADDR 0xa0
#define W_QUEUE_USED_HIGH_ADDR 0xa4

#define BLK_MAGIC 0x74726976
#define DEVICE_VERSION 2
#define DEVICE_ID 2
#define VENDOR_ID 0x12345678

#define VIRTIO_BLK_T_IN 0
#define VIRTIO_BLK_T_OUT 1